- name: ansible to install software
  ansible.builtin.pip:
    name: 
    - PyMySQL
  executable: pip3.9

- name: mysql installation
  ansible.builtin.package:
    name: mysql-server
    state: present

- name: start my mysql server
  ansible.builtin.service:
    name: mysqld
    state: started
    enabled: yes
  
- name: connect my sql server
  community.mysql.mysql_info:
    login_user: root
    login_password: "{{ root_password }}"
    login_host: "{{ host }}"
    ignore_errors: true
    register: mysql_info

- name: mysql_info print
  ansible.builtin.debug:
    msg: "{{ mysql_info }}"

- name: instal my sql root root_password
  ansible.builtin.command: "mysql_secure_installation --set-root-pass {{ root_password }}"
  when mysql_info.failed is true.